name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: chmod -R 777 output
      - run: docker-compose build
      - run: npm install
      - run: npm test
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output
